name: pvs-generation
channels:
  - conda-forge
  - defaults
  - pip:
      - matplotlib==3.8.4
      - nibabel==5.2.1
      - numba==0.60.0
      - numpy==1.26.4
      - pandas==2.2.2
      - scikit-image==0.22.0
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - tqdm==4.67.1